#file roles/nginx/tasks/conf.yml
---

- name: Place config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
    - { src: app.conf.j2, dest: "/etc/nginx/conf.d/{{ app_name }}.conf" }
  notify:
    - restart nginx

